import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Header from '@/components/header';
import { SESSION_COOKIE_NAME } from '@/constants';
import './globals.css';
import ProviderWrapper from '@/components/ProviderWrapper'; // Adjust the import path as necessary

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = cookies().get(SESSION_COOKIE_NAME)?.value || null;

  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProviderWrapper>
          <Header session={session} />
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
